In [3]:
!pip install numpy

In [4]:
import numpy as np


Create

In [5]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [6]:
data

array([[[0.6665153 , 0.38794641, 0.79701477, 0.51425981],
        [0.76286871, 0.52891634, 0.00873656, 0.81671207],
        [0.74252355, 0.22787815, 0.26794075, 0.02177878]],

       [[0.38370799, 0.06082015, 0.8548143 , 0.48758651],
        [0.58296561, 0.75399342, 0.14005816, 0.5185509 ],
        [0.02866196, 0.26259479, 0.03295016, 0.75730273]]])

In [7]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
arr =  np.array([[1,2,3,4], [1,2,42,3]])

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 1,  2, 42,  3]])

In [12]:
type(arr)

numpy.ndarray

Read

In [16]:
shape = data.shape #dimensions of array

size = data.size #total number of element in array
types = data.dtype #gives the type of data in array

In [19]:
# Slicing: similar to normal slicing
arr = data[0]
reverse = data[-1] # last value specified
slicer = data[0][0:2]
single_value = data[0][0][1]

In [21]:
single_value, arr, reverse, slicer

(0.38794640653301404,
 array([[0.6665153 , 0.38794641, 0.79701477, 0.51425981],
        [0.76286871, 0.52891634, 0.00873656, 0.81671207],
        [0.74252355, 0.22787815, 0.26794075, 0.02177878]]),
 array([[0.38370799, 0.06082015, 0.8548143 , 0.48758651],
        [0.58296561, 0.75399342, 0.14005816, 0.5185509 ],
        [0.02866196, 0.26259479, 0.03295016, 0.75730273]]),
 array([[0.6665153 , 0.38794641, 0.79701477, 0.51425981],
        [0.76286871, 0.52891634, 0.00873656, 0.81671207]]))

Update

In [23]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [24]:
list2, list1

(array([0.72095673, 0.73397355, 0.9178119 , 0.91669791, 0.09243351,
        0.89340639, 0.02497122, 0.90916697, 0.33023229, 0.11643543]),
 array([0.64296277, 0.96313594, 0.97514506, 0.07810477, 0.83988631,
        0.8528423 , 0.22480897, 0.90653708, 0.66328997, 0.41293056]))

In [28]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
mult = np.multiply(list1, list2)
div = np.divide(list1, list2)
dot = np.dot(list1, list2)

In [32]:
add, sub, mult, div, dot

(array([1.3639195 , 1.69710949, 1.89295696, 0.99480269, 0.93231982,
        1.7462487 , 0.24978019, 1.81570405, 0.99352226, 0.52936598]),
 array([-0.07799395,  0.22916239,  0.05733316, -0.83859314,  0.7474528 ,
        -0.04056409,  0.19983776, -0.00262989,  0.33305768,  0.29649513]),
 array([0.46354834, 0.70691631, 0.89499974, 0.07159848, 0.07763364,
        0.76193477, 0.00561375, 0.82419357, 0.21903977, 0.04807975]),
 array([0.89181882, 1.31222159, 1.06246723, 0.0852023 , 9.08638335,
        0.95459615, 9.00272439, 0.99710737, 2.00855576, 3.54643402]),
 4.073558103863051)

In [35]:
# Stat functions
sqrt =  np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,6)
exp = np.exp([2,3]) # creates e^x for x to be element of array
min = np.min(list1)
max = np.max(list1)

In [36]:
sqrt, ab, power, exp, min, max

(5.0,
 2,
 64,
 array([ 7.3890561 , 20.08553692]),
 0.07810477413374717,
 0.975145061008479)

In [37]:
data

array([[[0.6665153 , 0.38794641, 0.79701477, 0.51425981],
        [0.76286871, 0.52891634, 0.00873656, 0.81671207],
        [0.74252355, 0.22787815, 0.26794075, 0.02177878]],

       [[0.38370799, 0.06082015, 0.8548143 , 0.48758651],
        [0.58296561, 0.75399342, 0.14005816, 0.5185509 ],
        [0.02866196, 0.26259479, 0.03295016, 0.75730273]]])

In [38]:
data[0][0][0]

0.6665153001987231

In [39]:
data[0][0][0] = 700

In [50]:
data

array([[[8.73656001e-03, 2.27878151e-01, 2.67940747e-01, 7.42523555e-01],
        [2.17787761e-02, 5.14259805e-01, 7.62868708e-01, 8.16712073e-01],
        [3.87946407e-01, 5.28916337e-01, 7.97014772e-01, 7.00000000e+02]],

       [[2.86619608e-02, 3.29501590e-02, 2.62594791e-01, 7.53993422e-01],
        [6.08201510e-02, 3.83707985e-01, 4.87586510e-01, 7.57302731e-01],
        [1.40058163e-01, 5.18550896e-01, 5.82965615e-01, 8.54814297e-01]]])

In [51]:
data.sort()

In [52]:
data

array([[[8.73656001e-03, 2.27878151e-01, 2.67940747e-01, 7.42523555e-01],
        [2.17787761e-02, 5.14259805e-01, 7.62868708e-01, 8.16712073e-01],
        [3.87946407e-01, 5.28916337e-01, 7.97014772e-01, 7.00000000e+02]],

       [[2.86619608e-02, 3.29501590e-02, 2.62594791e-01, 7.53993422e-01],
        [6.08201510e-02, 3.83707985e-01, 4.87586510e-01, 7.57302731e-01],
        [1.40058163e-01, 5.18550896e-01, 5.82965615e-01, 8.54814297e-01]]])

In [53]:
data

array([[[8.73656001e-03, 2.27878151e-01, 2.67940747e-01, 7.42523555e-01],
        [2.17787761e-02, 5.14259805e-01, 7.62868708e-01, 8.16712073e-01],
        [3.87946407e-01, 5.28916337e-01, 7.97014772e-01, 7.00000000e+02]],

       [[2.86619608e-02, 3.29501590e-02, 2.62594791e-01, 7.53993422e-01],
        [6.08201510e-02, 3.83707985e-01, 4.87586510e-01, 7.57302731e-01],
        [1.40058163e-01, 5.18550896e-01, 5.82965615e-01, 8.54814297e-01]]])

In [74]:
data =  data.reshape((2,2,-1))

In [75]:
data.shape

(2, 2, 6)

In [76]:
zeroes = np.zeros(2)
print(zeroes)
zeroes = np.append(zeroes, [4,3])
print(zeroes)

[0. 0.]
[0. 0. 4. 3.]


In [77]:
# to insert at a specific place
zeroes = np.insert(zeroes, 3, [4,3,5])
zeroes

array([0., 0., 4., 4., 3., 5., 3.])

Delete

In [78]:
data

array([[[8.73656001e-03, 2.27878151e-01, 2.67940747e-01, 7.42523555e-01,
         2.17787761e-02, 5.14259805e-01],
        [7.62868708e-01, 8.16712073e-01, 3.87946407e-01, 5.28916337e-01,
         7.97014772e-01, 7.00000000e+02]],

       [[2.86619608e-02, 3.29501590e-02, 2.62594791e-01, 7.53993422e-01,
         6.08201510e-02, 3.83707985e-01],
        [4.87586510e-01, 7.57302731e-01, 1.40058163e-01, 5.18550896e-01,
         5.82965615e-01, 8.54814297e-01]]])

In [80]:
np.delete(data, 0, axis=1)
# axis here specifies how to delete the array, axis = 1 deletes horizontally that is alopng rows
# axis = 0 delete along columns

array([[[7.62868708e-01, 8.16712073e-01, 3.87946407e-01, 5.28916337e-01,
         7.97014772e-01, 7.00000000e+02]],

       [[4.87586510e-01, 7.57302731e-01, 1.40058163e-01, 5.18550896e-01,
         5.82965615e-01, 8.54814297e-01]]])

In [81]:
np.save("new array", data)

In [82]:
new = np.load("new array.npy")
new

array([[[8.73656001e-03, 2.27878151e-01, 2.67940747e-01, 7.42523555e-01,
         2.17787761e-02, 5.14259805e-01],
        [7.62868708e-01, 8.16712073e-01, 3.87946407e-01, 5.28916337e-01,
         7.97014772e-01, 7.00000000e+02]],

       [[2.86619608e-02, 3.29501590e-02, 2.62594791e-01, 7.53993422e-01,
         6.08201510e-02, 3.83707985e-01],
        [4.87586510e-01, 7.57302731e-01, 1.40058163e-01, 5.18550896e-01,
         5.82965615e-01, 8.54814297e-01]]])